services:
  mysql:
    image: mysql:8.0.35
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=tuf_intern
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=12345678
      - PMA_PORT=3306
    ports:
      - 8080:80
    restart: unless-stopped
    depends_on:
      - mysql

volumes:
  mysql_data:
